### ISSUE TITLE
Installation instructions too implicit

### ISSUE THREAD

**Issue by joallard** [dejw/geany-on-rails#2]
I'm new to git and I have a hard time figuring out how to install this. I have no idea how to "just merg[e] the geany directory". An example on terminal would be helpful or just a link to an example.

**Comment by itsbmac** [comment]
I'm also having issues with this.  If you could address it, that would be awesome!

**Comment by dejw** [comment]
Fixed in latest commit.

**Comment by joallard** [comment]
Thank you!
